[colors]
foreground    = "#6b5c4d"
background    = "#f4f0ed"
cursor_bg     = "#6b5c4d"
cursor_border = "#6b5c4d"
cursor_fg     = "#f4f0ed"
selection_bg  = "#ded2c8"
selection_fg  = "#6b5c4d"
ansi = [
    "#e9e1db",
    "#d7898c",
    "#83b887",
    "#cc7f2b",
    "#abb9d6",
    "#be79bb",
    "#729893",
    "#867462"
    ]
brights = [
    "#ded2c8",
    "#c65333",
    "#659e69",
    "#c29830",
    "#485f84",
    "#854882",
    "#436460",
    "#6b5c4d"
    ]
