[colors]
foreground    = "#ece1d7"
background    = "#2a2520"
cursor_bg     = "#ece1d7"
cursor_border = "#ece1d7"
cursor_fg     = "#2a2520"
selection_bg  = "#4d453e"
selection_fg  = "#ece1d7"
ansi = [
    "#352f2a",
    "#b65c60",
    "#78997a",
    "#e49b5d",
    "#697893",
    "#b380b0",
    "#86a3a3",
    "#c1a78e"
    ]
brights = [
    "#4d453e",
    "#f17c64",
    "#99d59d",
    "#ebc06d",
    "#9aacce",
    "#ce9bcb",
    "#88b3b2",
    "#ece1d7"
    ]
