[colors]
foreground    = "#675C53"
background    = "#F2F0EF"
cursor_bg     = "#675C53"
cursor_border = "#675C53"
cursor_fg     = "#F2F0EF"
selection_bg  = "#D9D3CE"
selection_fg  = "#675C53"
ansi = ["#E6E2DF", "#D7898C", "#83B887", "#B28B2B", "#4C5B99", "#BE79BB", "#729893", "#9D8E81"]
brights = ["#D9D3CE", "#C65333", "#669C78", "#B28B2B", "#4C5B99", "#89477B", "#436463", "#827569"]
