[colors]
foreground    = "#E6E2DF"
background    = "#211F1D"
cursor_bg     = "#E6E2DF"
cursor_border = "#E6E2DF"
cursor_fg     = "#211F1D"
selection_bg  = "#3C3836"
selection_fg  = "#E6E2DF"
ansi = ["#2E2C29", "#BD8183", "#78997A", "#EBC06D", "#A3A9CE", "#B380B0", "#7B9695", "#C1A78E"]
brights = ["#3C3836", "#DE715B", "#85B695", "#EBC06D", "#A3A9CE", "#CF9BC2", "#89B3B6", "nil"]
